//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CropImage.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string PhotoPath { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> LangCode { get; set; }
    }
}
