//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CropImage.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slider
    {
        public int Id { get; set; }
        public string TitleTr { get; set; }
        public string TitleEn { get; set; }
        public string PhotoPath { get; set; }
        public string Description1Tr { get; set; }
        public string Description1En { get; set; }
        public string Description2Tr { get; set; }
        public string Description2En { get; set; }
        public Nullable<int> Orderby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
